In [1]:
import numpy as np

a = np.array([0,1])
b = np.array([1,0])

# Performs the dot product of two arrays
# That means it multiplies the elements of the arrays and sums them up.
np.dot(a,b)

0

In [2]:
X = np.array([[1,0],[0,1]])
Y = np.array([[0,1],[1,0]])
X + Y

array([[1, 1],
       [1, 1]])

In [5]:
X=np.array([[1,0,1],[2,2,2]]) 
X

out=X[0:2,2]
out

array([1, 2])

In [9]:
X=np.array([[1,0],[0,1]]) 

Y=np.array([[2,1],[1,2]]) 

print(X)
print(Y)

Z=np.dot(X,Y) 
print(Z)

[[1 0]
 [0 1]]
[[2 1]
 [1 2]]
[[2 1]
 [1 2]]


In [10]:
with open("Example1.txt","r") as file1: 

     file_stuff=file1.readline() 

print(file_stuff) 

Line 1



In [11]:
with open("Example3.txt","w") as file1: 

    file1.write("This is line C\n") 